---
global:
  scrape_interval: 10s
scrape_configs:
  - job_name: Application
    static_configs:
      - targets:
          - "opentelemetry-collector:9090"
  - job_name: OpenTelemetry-Collector
    static_configs:
      - targets:
          - "opentelemetry-collector:8888"
